import { calculateConfidence, scoreToReadinessLabel, scoreToRiskLevel, type AnalysisResult } from "@/lib/local-intelligence";
import { buildImprovedAnswer } from "./improved-answer-builder";
export function analyzeInterviewAnswerLocally(input:any): AnalysisResult & { improvedAnswer:string; dimensions:Record<string,number> } {
 const answer=String(input.answer??""); const lower=answer.toLowerCase();
 const warnings:string[]=[]; if(answer.length<40) warnings.push("Answer is too short."); if((lower.match(/\b(thing|stuff|good|nice|okay)\b/g)||[]).length>2) warnings.push("Answer is too vague."); if(!lower.includes("university")) warnings.push("Missing university explanation."); if(!lower.includes("program")) warnings.push("Missing program explanation."); if(!/sponsor|finance|fund/i.test(lower)) warnings.push("Missing sponsor or finance explanation."); if(!/future|after graduation|career/i.test(lower)) warnings.push("Missing future plan."); if(/fake|lie|invent|make up/i.test(lower)) warnings.push("Dishonest phrasing detected.");
 const score=Math.max(0,100-warnings.length*10);
 const dimensions={ relevance:Math.max(0,20-(warnings.includes("Answer is too vague.")?6:0)), specificity:Math.max(0,20-(warnings.includes("Answer is too vague.")?8:0)), consistency:Math.max(0,20-(warnings.some(w=>w.includes("Missing"))?6:0)), financialClarity:/sponsor|finance|fund/i.test(lower)?15:6, studyPlanClarity:/study|program/i.test(lower)?10:4, futurePlanClarity:/future|career|after graduation/i.test(lower)?10:4, languageClarity:Math.max(2,5-(warnings.includes("Answer is too short.")?2:0)) };
 const confidence=calculateConfidence({structuredFieldCount:3,requiredFieldCount:4,hasExtractedText:true,hasAttachments:false});
 return {score,readinessLabel:scoreToReadinessLabel(score),riskLevel:scoreToRiskLevel(score),summary:"Interview readiness evaluated with local rubric.",evidence:[],recommendations:warnings.slice(0,5).map((w,i)=>({id:`i-${i}`,priority:"Medium",title:"Interview improvement",action:w,reason:"Local interview rubric",module:"interview_practice"})),missingItems:[],warnings,confidence,officialVerificationRequired:true,improvedAnswer:buildImprovedAnswer(answer),dimensions};
}
