create extension if not exists "pgcrypto";
create table if not exists public.users_profile (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, full_name text, phone text, country text, target_country text, role text default 'user', created_at timestamptz default now());
create table if not exists public.program_profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, education_level text, field text, gpa text, english_level text, budget text, target_country text, preferred_intake text, career_goal text, score int, report_json jsonb, created_at timestamptz default now());
create table if not exists public.document_reviews (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, passport_status text, transcript_status text, english_status text, admission_status text, financial_docs_status text, score int, report_json jsonb, created_at timestamptz default now());
create table if not exists public.financial_reviews (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, sponsor_name text, sponsor_relation text, bank_name text, currency text, opening_balance numeric, closing_balance numeric, average_balance numeric, large_deposit_notes text, income_notes text, source_of_funds text, score int, report_json jsonb, created_at timestamptz default now());
create table if not exists public.interview_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, target_country text, visa_type text, difficulty text, score int, feedback_json jsonb, created_at timestamptz default now());
create table if not exists public.final_reports (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, program_score int, document_score int, financial_score int, interview_score int, overall_score int, risk_level text, report_json jsonb, created_at timestamptz default now());
create table if not exists public.uploads (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, file_name text not null, file_type text, module text, storage_path text not null, created_at timestamptz default now());
insert into storage.buckets (id, name, public) values ('brovi-private-uploads','brovi-private-uploads',false) on conflict (id) do update set public=false;
