export type AttachmentType = { key:string; label:string; accepted:string[]; preferred:string; required?:boolean; notes:string; sensitivity:"low"|"medium"|"high"; subtypes?:string[] };
export const attachmentTypes: AttachmentType[] = [
{key:"valid_passport",label:"Valid Passport",accepted:["pdf","jpg","jpeg","png"],preferred:"pdf",required:true,notes:"Upload passport bio-data page or complete passport PDF when required.",sensitivity:"medium"},
{key:"passport_photo",label:"Passport Photo",accepted:["jpg","jpeg","png","pdf"],preferred:"jpg/png",notes:"Use clear photo file if required by the institution or visa platform.",sensitivity:"low"},
{key:"transcript_msc",label:"Transcript of Records for MSc Applicants",accepted:["pdf"],preferred:"pdf",notes:"For master's applicants. Upload full bachelor transcript or equivalent academic record.",sensitivity:"medium"},
{key:"transcript_bsc",label:"Transcript of Records for BSc Applicants",accepted:["pdf"],preferred:"pdf",notes:"For bachelor's applicants. Upload secondary school or preparatory transcript where applicable.",sensitivity:"medium"},
{key:"final_diploma",label:"Final Diploma / Degree",accepted:["pdf"],preferred:"pdf",notes:"Upload final awarded diploma or degree certificate.",sensitivity:"medium"},
{key:"provisional_degree",label:"Provisional Degree / Temporary Certificate of Graduation",accepted:["pdf"],preferred:"pdf",notes:"Use when the final diploma is not yet issued.",sensitivity:"medium"},
{key:"legalized_documents",label:"Legalized Documents",accepted:["pdf"],preferred:"pdf",notes:"Upload officially legalized, apostilled, or certified versions when required.",sensitivity:"medium"},
{key:"english_proficiency",label:"English Proficiency",accepted:["pdf"],preferred:"pdf",notes:"Upload only valid proof accepted by the target university or authority.",sensitivity:"medium",subtypes:["Medium of Instruction","IELTS","TOEFL","Duolingo English Test","Cambridge English","PTE Academic","Other international English proficiency proof"]},
{key:"higher_eligibility",label:"Higher Education Eligibility Certificate",accepted:["pdf"],preferred:"pdf",notes:"Upload certificate proving eligibility for higher education when applicable.",sensitivity:"medium"},
{key:"cv",label:"Curriculum Vitae",accepted:["pdf"],preferred:"pdf",notes:"Upload an updated academic CV.",sensitivity:"low"},
{key:"motivation_letter",label:"Motivation Letter / Statement of Purpose",accepted:["pdf"],preferred:"pdf",notes:"Upload the latest version prepared for the selected program.",sensitivity:"low"},
{key:"recommendation_letter",label:"Recommendation Letter",accepted:["pdf"],preferred:"pdf",notes:"Upload academic or professional recommendation letter when required.",sensitivity:"low"},
{key:"admission_letter",label:"Admission Letter / Offer Letter",accepted:["pdf"],preferred:"pdf",notes:"Upload university admission, eligibility, or offer document.",sensitivity:"medium"},
{key:"pre_enrollment_proof",label:"Pre-enrolment / Admission Portal Proof",accepted:["pdf","jpg","jpeg","png"],preferred:"pdf",notes:"Upload proof from admission or pre-enrolment portal when available.",sensitivity:"low"},
{key:"declaration_of_value",label:"Declaration of Value",accepted:["pdf"],preferred:"pdf",notes:"Use when required by the institution or Italian process.",sensitivity:"medium"},
{key:"cimea",label:"CIMEA Statement",accepted:["pdf"],preferred:"pdf",notes:"Use when required by the institution or procedure.",sensitivity:"medium"},
{key:"bank_statement",label:"Bank Statement",accepted:["pdf"],preferred:"pdf",notes:"Do not upload card numbers, passwords, OTPs, or bank login details.",sensitivity:"high"},
{key:"sponsor_letter",label:"Sponsor Letter",accepted:["pdf"],preferred:"pdf",notes:"Upload signed sponsor support letter.",sensitivity:"medium"},
{key:"sponsor_relationship",label:"Sponsor Relationship Proof",accepted:["pdf","jpg","jpeg","png"],preferred:"pdf",notes:"Upload birth certificate or family proof when relevant.",sensitivity:"medium"},
{key:"sponsor_business",label:"Sponsor Business / Employment Proof",accepted:["pdf"],preferred:"pdf",notes:"Upload job letter, business license, tax proof, or income proof where relevant.",sensitivity:"high"},
{key:"accommodation",label:"Accommodation Proof",accepted:["pdf","jpg","jpeg","png"],preferred:"pdf",notes:"Upload housing confirmation, booking, or host declaration where required.",sensitivity:"medium"},
{key:"travel_insurance",label:"Travel Insurance",accepted:["pdf"],preferred:"pdf",notes:"Upload travel or health insurance when required.",sensitivity:"medium"},
{key:"police_clearance",label:"Police Clearance",accepted:["pdf"],preferred:"pdf",notes:"Upload when required by destination country or institution.",sensitivity:"medium"},
{key:"medical_certificate",label:"Medical Certificate",accepted:["pdf"],preferred:"pdf",notes:"Upload when required.",sensitivity:"medium"},
{key:"embassy_appointment",label:"Embassy Appointment Proof",accepted:["pdf","jpg","jpeg","png"],preferred:"pdf",notes:"Upload appointment receipt or confirmation where available.",sensitivity:"low"},
{key:"other_attachment",label:"Other Attachment",accepted:["pdf","jpg","jpeg","png"],preferred:"pdf",notes:"Use only when the document does not match the listed categories.",sensitivity:"medium"},
];
