"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { RiskBadge } from "@/components/scores/RiskBadge";
import { EmptyState } from "@/components/ui/EmptyState";

const categories = ["Identity", "Academic", "Financial", "Admission", "Visa", "Sponsor", "Other"];
const statuses = ["Missing", "Available", "Needs Translation", "Needs Legalization", "Expired", "Ready"];
const riskScore: Record<string, number> = { Missing: 25, Expired: 20, "Needs Translation": 55, "Needs Legalization": 55, Available: 75, Ready: 92 };
type VaultItem = { id: string; document_name: string; category: string | null; status: string; expiry_date: string | null; translation_needed: boolean; legalization_needed: boolean; storage_path: string | null; notes: string | null };

export function DocumentVaultClient() {
  const supabase = createClient();
  const [items, setItems] = useState<VaultItem[]>([]);
  const [form, setForm] = useState({ document_name: "", category: "Identity", status: "Missing", expiry_date: "", translation_needed: false, legalization_needed: false, notes: "" });
  const [file, setFile] = useState<File | null>(null);
  const [message, setMessage] = useState("");
  async function load() { if (!supabase) return; const { data: user } = await supabase.auth.getUser(); if (!user.user) return; const { data } = await supabase.from("document_vault_items").select("*").eq("user_id", user.user.id).order("created_at", { ascending: false }); setItems((data ?? []) as VaultItem[]); }
  useEffect(() => { void load(); }, []);
  async function add(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase) return setMessage("Database connection is not configured."); const { data: user } = await supabase.auth.getUser(); if (!user.user) return setMessage("Sign in to save documents."); let storage_path = null; if (file) { const safe = file.name.replace(/[^a-zA-Z0-9._-]/g, "-"); storage_path = `${user.user.id}/document-vault/${Date.now()}-${safe}`; const upload = await supabase.storage.from("brovi-private-documents").upload(storage_path, file); if (upload.error) return setMessage("File upload failed. Please try again."); await supabase.from("uploads").insert({ user_id: user.user.id, file_name: file.name, file_type: file.type, module: "document-vault", storage_path }); } const { error } = await supabase.from("document_vault_items").insert({ ...form, storage_path, user_id: user.user.id }); if (error) setMessage("Document item could not be saved."); else { setForm({ document_name: "", category: "Identity", status: "Missing", expiry_date: "", translation_needed: false, legalization_needed: false, notes: "" }); setFile(null); await load(); } }
  return <div className="space-y-5"><div className="card border-amber-200 bg-amber-50 text-amber-900 dark:border-amber-400/30 dark:bg-amber-400/10 dark:text-amber-100">Do not upload passwords, card numbers, or bank login details. Files are stored privately for your BROVI Scan account.</div><form className="card grid gap-3 md:grid-cols-3" onSubmit={add}><input className="input" placeholder="Document name" required value={form.document_name} onChange={(e) => setForm({ ...form, document_name: e.target.value })} /><select className="input" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{categories.map((c) => <option key={c}>{c}</option>)}</select><select className="input" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{statuses.map((s) => <option key={s}>{s}</option>)}</select><input className="input" type="date" value={form.expiry_date} onChange={(e) => setForm({ ...form, expiry_date: e.target.value })} /><input className="input" placeholder="Notes" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /><input className="input" type="file" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /><label className="label flex items-center gap-2"><input type="checkbox" checked={form.translation_needed} onChange={(e) => setForm({ ...form, translation_needed: e.target.checked })} /> Translation needed</label><label className="label flex items-center gap-2"><input type="checkbox" checked={form.legalization_needed} onChange={(e) => setForm({ ...form, legalization_needed: e.target.checked })} /> Legalization needed</label><button className="btn-primary" type="submit">Save document</button>{message ? <p className="text-sm text-risk md:col-span-3">{message}</p> : null}</form>{items.length ? <div className="card overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-200 dark:border-white/10"><th className="py-3">Document</th><th>Category</th><th>Status</th><th>Risk</th><th>Expiry</th><th>Private file</th><th>Notes</th></tr></thead><tbody>{items.map((doc) => <tr key={doc.id} className="border-b border-slate-100 dark:border-white/5"><td className="py-3 font-semibold">{doc.document_name}</td><td>{doc.category}</td><td>{doc.status}</td><td><RiskBadge score={riskScore[doc.status] ?? 60} /></td><td>{doc.expiry_date || "—"}</td><td>{doc.storage_path ? "Stored privately" : "—"}</td><td className="muted">{doc.notes}</td></tr>)}</tbody></table></div> : <EmptyState title="No vault documents yet" description="Add documents and private upload metadata for your applications." />}</div>;
}
