"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { EmptyState } from "@/components/ui/EmptyState";

type Task = { id: string; title: string; description: string | null; due_date: string | null; priority: string | null; status: string; source_module: string | null };

export function TasksClient() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [form, setForm] = useState({ title: "", description: "", due_date: "", priority: "Medium", status: "To Do", source_module: "Manual" });
  const [filter, setFilter] = useState("All");
  const [message, setMessage] = useState("");
  const supabase = createClient();
  const visible = filter === "All" ? tasks : tasks.filter((task) => task.status === filter || task.priority === filter);
  const progress = useMemo(() => tasks.length ? Math.round((tasks.filter((task) => task.status === "Done").length / tasks.length) * 100) : 0, [tasks]);
  async function load() { if (!supabase) return; const { data: user } = await supabase.auth.getUser(); if (!user.user) return; const { data } = await supabase.from("tasks").select("*").eq("user_id", user.user.id).order("created_at", { ascending: false }); setTasks((data ?? []) as Task[]); }
  useEffect(() => { void load(); }, []);
  async function add(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!supabase) return setMessage("Database connection is not configured."); const { data: user } = await supabase.auth.getUser(); if (!user.user) return setMessage("Sign in to save tasks."); const { error } = await supabase.from("tasks").insert({ ...form, user_id: user.user.id }); if (error) setMessage("Task could not be saved."); else { setForm({ title: "", description: "", due_date: "", priority: "Medium", status: "To Do", source_module: "Manual" }); await load(); } }
  async function setStatus(id: string, status: string) { if (!supabase) return; await supabase.from("tasks").update({ status, updated_at: new Date().toISOString() }).eq("id", id); await load(); }
  return <div className="space-y-5"><div className="card"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Roadmap progress</h2><span className="font-black text-royal">{progress}%</span></div><div className="mt-3 h-3 rounded-full bg-slate-200 dark:bg-white/10"><div className="h-3 rounded-full bg-gradient-to-r from-royal to-cyan" style={{ width: `${progress}%` }} /></div></div><form className="card grid gap-3 md:grid-cols-4" onSubmit={add}><input className="input" placeholder="Task title" required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><input className="input" placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><input className="input" type="date" value={form.due_date} onChange={(e) => setForm({ ...form, due_date: e.target.value })} /><select className="input" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}>{["High", "Medium", "Low"].map((p) => <option key={p}>{p}</option>)}</select><button className="btn-primary md:col-span-4" type="submit">Add task</button>{message ? <p className="text-sm text-risk md:col-span-4">{message}</p> : null}</form><div className="card"><select className="input max-w-sm" value={filter} onChange={(e) => setFilter(e.target.value)}><option>All</option>{["To Do", "In Progress", "Done", "High", "Medium", "Low"].map((s) => <option key={s}>{s}</option>)}</select></div>{visible.length ? <div className="grid gap-3">{visible.map((task) => <article key={task.id} className="card flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-royal dark:bg-white/10">{task.priority}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold dark:bg-white/10">{task.status}</span>{task.due_date && new Date(task.due_date) < new Date() && task.status !== "Done" ? <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-700">Due soon</span> : null}</div><h3 className="mt-3 text-lg font-bold">{task.title}</h3><p className="muted">{task.description}</p><p className="mt-1 text-xs muted">Due {task.due_date ?? "not set"} · {task.source_module}</p></div><select className="input md:w-44" value={task.status} onChange={(event) => setStatus(task.id, event.target.value)}>{["To Do", "In Progress", "Done"].map((status) => <option key={status}>{status}</option>)}</select></article>)}</div> : <EmptyState title="No tasks yet" description="Add tasks from scan recommendations or create your first preparation action." />}</div>;
}
