"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { attachmentTypes } from "@/lib/documents/attachment-types";
import { validateAttachmentFile } from "@/lib/documents/file-validation";
import { getSignedDocumentUrl, uploadPrivateDocument } from "@/lib/documents/document-storage";
import { logDocumentAudit } from "@/lib/documents/document-audit";
import { AttachmentTypeSelect } from "./attachment-type-select";
import { AttachmentListTable, type AttachmentRow } from "./attachment-list-table";
import { FileSizeLabel } from "./file-size-label";

export function AttachmentUploadPanel(){
 const [typeKey,setTypeKey]=useState(""); const [file,setFile]=useState<File|null>(null); const [rows,setRows]=useState<AttachmentRow[]>([]); const [msg,setMsg]=useState(""); const [loading,setLoading]=useState(false);
 const supabase=createClient();
 async function load(){ if(!supabase) return; const {data:auth}=await supabase.auth.getUser(); if(!auth.user) return; const {data}=await supabase.from("document_attachments").select("id,attachment_label,file_name,file_size_bytes,status,created_at,storage_path").eq("user_id",auth.user.id).eq("module","document_scan").order("created_at",{ascending:false}); setRows((data as AttachmentRow[])||[]); }
 useEffect(()=>{load();},[]);
 async function attach(){ if(!file||!typeKey||!supabase) return; const type=attachmentTypes.find(t=>t.key===typeKey)!; const err=validateAttachmentFile(file,type); if(err) return setMsg(err); setLoading(true); const {data:auth}=await supabase.auth.getUser(); if(!auth.user){setMsg("Sign in required.");setLoading(false); return;} const exists=rows.find(r=>r.attachment_label===type.label && r.status!=="Removed") && type.key!=="other_attachment"; if(exists){setMsg("This attachment type already exists. Replace it or choose another type.");setLoading(false);return;} try{ const storage_path=await uploadPrivateDocument(auth.user.id,type.key,file); const {error}=await supabase.from("document_attachments").insert({user_id:auth.user.id,module:"document_scan",attachment_type_key:type.key,attachment_label:type.label,file_name:file.name,file_type:file.type,file_size_bytes:file.size,storage_path,status:"Uploaded",sensitivity:type.sensitivity}); if(error) throw error; await logDocumentAudit("document_uploaded",{attachment_type_key:type.key,file_name:file.name,file_size_bytes:file.size,sensitivity:type.sensitivity}); setTypeKey("");setFile(null);setMsg("Document attached."); await load(); }catch(e){setMsg("Upload failed. Please try again.");} setLoading(false);
 }
 async function onView(r:AttachmentRow){ try{const url=await getSignedDocumentUrl(r.storage_path); await logDocumentAudit("document_viewed",{attachment:r.attachment_label}); window.open(url,"_blank","noopener,noreferrer");}catch{setMsg("Could not open document.");}}
 async function onRemove(r:AttachmentRow){ if(!confirm("Remove this attachment?")) return; if(!supabase) return; await supabase.from("document_attachments").update({status:"Removed"}).eq("id",r.id); await logDocumentAudit("document_removed",{attachment:r.attachment_label}); await load(); }
 async function onReplace(r:AttachmentRow){ if(!file){setMsg("Choose a replacement file first."); return;} if(!supabase) return; const type=attachmentTypes.find(t=>t.label===r.attachment_label); if(!type){setMsg("Unknown attachment type.");return;} const err=validateAttachmentFile(file,type); if(err) return setMsg(err); const {data:auth}=await supabase.auth.getUser(); if(!auth.user) return; const path=await uploadPrivateDocument(auth.user.id,type.key,file); await supabase.from("document_attachments").update({status:"Replaced"}).eq("id",r.id); await supabase.from("document_attachments").insert({user_id:auth.user.id,module:"document_scan",attachment_type_key:type.key,attachment_label:type.label,file_name:file.name,file_type:file.type,file_size_bytes:file.size,storage_path:path,status:"Uploaded",sensitivity:type.sensitivity}); await logDocumentAudit("document_replaced",{attachment:r.attachment_label}); await load(); }
 return <div className="space-y-4 card"><h2 className="text-xl font-bold">Attach documents</h2><p className="muted">Select a document type, upload the file, and repeat until your application file is complete.</p><p className="text-sm font-semibold text-amber-700 dark:text-amber-300">Do not upload card numbers, bank login details, passwords, OTPs, or private account access.</p><div className="grid gap-3 md:grid-cols-3"><AttachmentTypeSelect value={typeKey} onChange={setTypeKey} /><input className="input" type="file" onChange={(e)=>setFile(e.target.files?.[0]??null)} /><button className="btn-primary" type="button" disabled={loading} onClick={attach}>{loading?"Attaching...":"Attach document"}</button></div><FileSizeLabel />{msg?<p className="text-sm text-risk">{msg}</p>:null}<AttachmentListTable rows={rows} onView={onView} onReplace={onReplace} onRemove={onRemove} /></div>;
}
