import type { CountryData, CountryRiskFlag, DocumentItem, InterviewQuestionGroup, RecommendedTaskTemplate } from "./types";
const item = (key:string,label:string,notes:string,importance:DocumentItem["importance"]="important",mayBeRequired=false):DocumentItem=>({key,label,notes,importance,verificationLevel:mayBeRequired?"case_specific":"official_source",verifyOfficially:true,mayBeRequired});
export const createPassportItem=()=>item("passport","Valid passport","Must be valid across the planned application and travel timeline.","critical");
export const createPhotoItem=()=>item("photo","Passport photo","Photo format may be required by visa or admission portal.","important",true);
export const createAdmissionLetterItem=()=>item("admission_letter","Admission letter","Provide the latest admission or eligibility confirmation from the institution.","critical");
export const createAcademicTranscriptItem=()=>item("transcript","Academic transcript","Include complete grades and official records.","critical");
export const createCertificateItem=()=>item("certificate","Academic certificate","Degree or completion certificate may be required.","important",true);
export const createEnglishProofItem=()=>item("language_proof","Language proof","English or local-language evidence may be required by institution or visa process.","important",true);
export const createFinancialProofItem=()=>item("financial_proof","Financial proof","Show that tuition and living costs can be covered.","critical");
export const createSponsorLetterItem=()=>item("sponsor_letter","Sponsor letter","If sponsored, include signed support letter.","important",true);
export const createSponsorRelationshipProofItem=()=>item("sponsor_relationship","Sponsor relationship proof","Evidence of relationship may be required.","important",true);
export const createCVItem=()=>item("cv","CV","Use a current CV aligned with your study plan.","supporting");
export const createMotivationLetterItem=()=>item("motivation_letter","Motivation letter","Explain fit, study goals, and career direction.","important");
export const createAccommodationProofItem=()=>item("accommodation_proof","Accommodation proof","Initial housing evidence may be required.","case_specific",true);
export const createInsuranceItem=()=>item("insurance","Insurance proof","Health or travel insurance may be required by route.","case_specific",true);
export const createTranslationLegalizationItem=()=>item("translation_legalization","Translation/legalization proof","Non-local-language documents may need certified translation or legalization.","important",true);
export const createOfficialVerificationMessage=(countryName:string)=>`Country guidance for ${countryName} is a preparation aid. Verify final requirements with official authorities, the selected institution, and the relevant embassy or consulate before submission.`;
export const interviewGroups: InterviewQuestionGroup[]=["Study plan","University choice","Program choice","Sponsor and finance","Academic background","Future plan","Refusal or gap explanation","Return plan"].map((t,i)=>({key:`group_${i+1}`,title:t,purpose:`Assess ${t.toLowerCase()} clarity and consistency.`,questions:[`Explain your ${t.toLowerCase()} in clear steps.`,`What evidence supports your ${t.toLowerCase()}?`,`How does your ${t.toLowerCase()} match your long-term profile?`]}));
export const riskFlags: CountryRiskFlag[]=[
{key:"missingAdmissionDocument",title:"Missing admission document",description:"Core admission evidence is missing.",severity:"high"},{key:"missingFinancialProof",title:"Missing financial proof",description:"No clear tuition/living support evidence.",severity:"high"},{key:"unclearSourceOfFunds",title:"Unclear source of funds",description:"Source of funds is not documented clearly.",severity:"high"},{key:"nameMismatch",title:"Name mismatch",description:"Document names do not match across records.",severity:"medium"},{key:"expiredPassport",title:"Expired passport risk",description:"Passport validity may be insufficient.",severity:"high"},{key:"missingTranslation",title:"Missing translation/legalization",description:"Required translation/legalization evidence is missing.",severity:"medium"},{key:"missingOfficialVerification",title:"Official verification pending",description:"Checklist has not been verified against official source.",severity:"medium"},{key:"largeDepositWithoutExplanation",title:"Large deposit not explained",description:"Large deposits need documentary explanation.",severity:"high"},{key:"weakProgramFit",title:"Weak program fit",description:"Program choice and profile alignment is not strong.",severity:"medium"},{key:"weakInterviewAnswer",title:"Weak interview answer quality",description:"Answers are generic or inconsistent.",severity:"medium"}
];
export const taskTemplates: RecommendedTaskTemplate[]=[
{key:"collect_critical_docs",title:"Collect critical missing documents",description:"Prioritize missing critical items first.",sourceModule:"document_scan",priority:"High"},{key:"verify_official_checklist",title:"Verify official checklist",description:"Check embassy/institution requirements before submission.",sourceModule:"document_scan",priority:"High"},{key:"prepare_finance_explanation",title:"Prepare source-of-funds explanation",description:"Document sponsor relationship and fund origin.",sourceModule:"bank_statement_scan",priority:"High"},{key:"prepare_interview_answers",title:"Prepare interview answers",description:"Practice country-specific questions with clear examples.",sourceModule:"interview_practice",priority:"Medium"},{key:"confirm_translation",title:"Confirm translation/legalization",description:"Validate translation/legalization requirements early.",sourceModule:"document_vault",priority:"Medium"},{key:"readiness_review",title:"Run final readiness review",description:"Recheck weak points before submission.",sourceModule:"readiness_report",priority:"Medium"}
];
export const baseDisclaimer="Brovi Scan provides preparation guidance only. Final decisions are made by universities, embassies, consulates, immigration authorities, and scholarship providers.";
export const withBase=(pack:CountryData):CountryData=>pack;
