import { calculateConfidence, scoreToReadinessLabel, scoreToRiskLevel, type AnalysisResult } from "@/lib/local-intelligence";
import { averageCoverageRatio, coverageRatio, monthlyNet, totalRequiredFunds } from "./financial-formulas";
import { detectFinancialRedFlags } from "./financial-red-flags";
export function analyzeFinancialLocally(input:any): AnalysisResult & { coverageRatio:number; averageCoverageRatio:number; redFlags:string[]; strengths:string[]; sponsorExplanationTemplate:string } {
 const tuition=Number(input.tuitionFeeAmount??input.tuitionFee??0),living=Number(input.livingCostAmount??input.livingCost??0),closing=Number(input.closingBalance??0),avg=Number(input.averageBalance??0),income=Number(input.monthlyIncome??0),expenses=Number(input.monthlyExpenses??0);
 const total=totalRequiredFunds(tuition,living); const cov=coverageRatio(closing,total); const avgCov=averageCoverageRatio(avg,total); const net=monthlyNet(income,expenses); const flags=detectFinancialRedFlags(input);
 let score=0; score += Math.min(30,Math.max(0,cov*30)); score += Math.min(20,Math.max(0,avgCov*20)); score += net>=0?15:5; score += String(input.sourceOfFunds??"").length>=20?15:5; score += input.sponsorRelation&&input.sponsorProofAvailable?10:3; score += input.accommodationProof?5:2; score += input.bankName&&input.currency?5:2; score = Math.max(0,Math.min(100,Math.round(score-flags.length*2)));
 const confidence=calculateConfidence({structuredFieldCount:10,requiredFieldCount:12,hasExtractedText:false,hasAttachments:false});
 return {score,readinessLabel:scoreToReadinessLabel(score),riskLevel:scoreToRiskLevel(score),summary:"Financial readiness is preparation guidance. The official authority decides whether the proof is acceptable.",evidence:[],recommendations:flags.slice(0,5).map((f,idx)=>({id:`f-${idx}`,priority:"High",title:"Resolve financial risk",action:f,reason:"Local financial rules engine",module:"bank_statement_scan"})),missingItems:[],warnings:[],confidence,officialVerificationRequired:true,coverageRatio:cov,averageCoverageRatio:avgCov,redFlags:flags,strengths:[cov>=1?"Closing balance covers estimated required funds.":"Increase available closing balance coverage.",net>=0?"Monthly net flow is positive.":"Monthly expenses exceed income."],sponsorExplanationTemplate:"The sponsor is [relationship]. Funds come from [source]. Evidence includes [bank statements, sponsor proof, relationship documents]."};
}
