import type { AIReport, RiskLevel, ScoreInput } from "@/types";
export function clampScore(score:number){return Math.max(0,Math.min(100,Math.round(score)));}
export function riskLevel(score:number): RiskLevel { if(score<40)return "High Risk"; if(score<60)return "Needs Work"; if(score<75)return "Moderate"; if(score<90)return "Strong"; return "Very Strong"; }
const filled=(v:unknown)=>Array.isArray(v)?v.length>0: v!==undefined && v!==null && String(v).trim().length>0;
export function scoreByCompleteness(input:ScoreInput, weights:Record<string,number>){ return clampScore(Object.entries(weights).reduce((s,[k,w])=>s+(filled(input[k])?w:0),0)); }
export function programFallback(input:ScoreInput):AIReport{ const score=scoreByCompleteness(input,{educationLevel:15,field:10,gpa:15,englishLevel:15,budget:15,targetCountry:10,availableDocuments:10,careerGoal:10}); return base(score,["Profile details were reviewed with deterministic scoring.","Career and study preferences are captured."],["AI feedback is unavailable until GEMINI_API_KEY is configured.","Improve any missing academic, language, budget, or document details."]); }
export function documentFallback(input:ScoreInput):AIReport{ const score=scoreByCompleteness(input,{passportStatus:10,transcriptStatus:20,translationStatus:15,admissionStatus:20,cvStatus:15,financialDocsStatus:10,otherStatus:10}); return base(score,["Document checklist is organized."],["Missing, unclear, expired, untranslated, or unlegalized documents reduce readiness."]); }
export function financeFallback(input:ScoreInput):AIReport{ const opening=Number(input.openingBalance||0), closing=Number(input.closingBalance||0), avg=Number(input.averageBalance||0), need=Number(input.tuitionFeeAmount||0)+Number(input.livingCostAmount||0); let score=0; if(avg>=need&&need>0)score+=30; else if(avg>0)score+=15; if(opening>0&&closing>0)score+=20; if(filled(input.sourceOfFunds))score+=20; if(filled(input.sponsorRelation))score+=10; if(filled(input.sponsorJobProof))score+=10; if(!filled(input.largeDeposits))score+=10; return base(clampScore(score),["Safe financial fields were collected without bank logins or card details."],["Explain large deposits, sponsor relationship, and source of funds clearly."]); }
export function interviewFallback(input:ScoreInput):AIReport{ const answer=String(input.answer||""); const score=clampScore(Math.min(85, 30 + answer.split(/\s+/).filter(Boolean).length * 2 + (answer.includes("because")?10:0))); return base(score,["Answer submitted for clarity and relevance review."],["Add specific program, sponsor, study plan, and return-plan details."]); }
export function finalFallback(input:ScoreInput):AIReport{ const score=clampScore((Number(input.programScore||0)+Number(input.documentScore||0)+Number(input.financialScore||0)+Number(input.interviewScore||0))/4); return base(score,["Scores are consolidated evenly across the four scan modules."],["Complete weaker modules before submission."]); }
function base(score:number,strengths:string[],weaknesses:string[]):AIReport{return{score,riskLevel:riskLevel(score),strengths,weaknesses,recommendations:["Review all missing fields and supporting documents.","Practice concise, truthful answers before submission.","Request BROVI Consultant Review for human preparation support."],stepByStepPlan:["Complete profile and target-country details.","Resolve missing or unclear documents.","Prepare financial explanations and proof.","Practice interview answers and regenerate readiness report."],warning:"AI feedback is unavailable. Basic scoring mode is active."};}
