import { DashboardShell } from "@/components/layout/DashboardShell";
import { ScanForm } from "@/components/forms/ScanForm";
import { UploadBox } from "@/components/forms/UploadBox";
import { documentStatuses } from "@/lib/constants/copy";

export const dynamic = "force-dynamic";
const docs = [["Identity document status (passport/national ID)","passportStatus"],["Academic transcript status","transcriptStatus"],["Grade 12 or previous certificate status","grade12Certificate"],["Entrance exam result status when applicable","entranceExamResult"],["CV status","cvStatus"],["Motivation letter status","motivationLetterStatus"],["Recommendation letter status","recommendationLetterStatus"],["Language proof status","englishStatus"],["Declaration of Value status when applicable","declarationOfValueStatus"],["CIMEA status when applicable","cimeaStatus"],["Admission document status","admissionStatus"],["Pre-enrolment or admission portal proof status","preEnrollmentStatus"],["Sponsor letter status","sponsorshipLetterStatus"],["Birth certificate status when required","birthCertificateStatus"],["Police clearance status when required","policeClearanceStatus"],["Travel insurance status when required","travelInsuranceStatus"],["Translation status","translationStatus"],["Financial support document status","financialDocsStatus"],["Country-specific document status","otherStatus"]];
const fields = docs.map(([label,name]) => ({ label, name, options: documentStatuses, helper: "Select the current status. Verify official requirements on embassy/university websites before submission." }));
export default function Page() {
  return <DashboardShell><h1 className="section-title">Document Scan</h1><p className="muted">Sections: Identity documents, Academic documents, Admission documents, Financial/Sponsor documents, Translation/Legalization, Country-specific documents.</p><div className="card text-sm"><p><strong>Italy:</strong> Universitaly pre-enrolment may be relevant. Declaration of Value or CIMEA may be required depending on the university and procedure. Official requirements must be verified with the institution and embassy. Verify current requirements on the official website before submission.</p><p className="mt-2"><strong>Germany:</strong> Valid passport, completed application form, biometric photo, admission-related documents, language proof, and financial proof may be relevant. Official checklist must be verified with the German Embassy page. Verify current requirements on the official website before submission.</p><p className="mt-2"><strong>Canada:</strong> Letter of acceptance, PAL/TAL in most cases, proof of identity, and proof of financial support may be relevant. Quebec may require CAQ instead of PAL/TAL. Verify current requirements on the official website before submission.</p></div><UploadBox label="Optional private document upload" /><ScanForm fields={fields} endpoint="/api/analyze-documents" submitLabel="Review documents" tableName="document_reviews" /></DashboardShell>;
}
